### ISSUE TITLE
crash moments after starting plugin

### ISSUE THREAD

**Issue by micsthepick** [james34602/SpleeterRT#1]
Tested with audacity and VSTHost, in both cases the plugin does not work correctly, and crashes a short while after it is loaded. Unsure what is causing the issue, but the coefficients are present.

I would also like to see if it's possible to run this with EqualizerAPO, and I know that this might be a seperate issue, as it runs the plugins as the audio service user. (Even ignoring that potential issue, it also crashes the same way there).

**Comment by james34602** [comment]
It's most likely due to Intel MKL compatibility problem.
Compile with plain CPU mode will most likely solve the problem.

For EqualizerAPO, it's most likely not working no matter what reason, because the instantaneous CPU load is so large, audiodg.exe will crash itself, I think this is due to audio thread limitation.

By the way, even if it runs on EqualizerAPO won't give you real time processing, I'm not here to tell what method/modification can make SpleeterRT output samples in true real time, this repo is mostly likely demonstrate the computation speed up, but of course, there's way to accomplish the idea.

**Comment by micsthepick** [comment]
I can get EAPO to work on the latest version of this plugin by adding the coefficients to C:\Windows\ServiceProfiles\LocalService. It still doesn't sound as effective at separation as I'd expect.
EDIT: Turns out only the 256T plugin works, the 128 one must have been causing crashes
