### ISSUE TITLE
Compare SpleeterRT, Spleeter And Original Spectrum

### ISSUE THREAD

**Issue by Jongan** [james34602/SpleeterRT#7]
SpleeterRT is very different from the original spectrum, but Deezer Spleeter is very close to the original spectrum. Why? There are something wrong with SpleeterRT？

**Comment by james34602** [comment]
Please read this [Readme.md](https://github.com/james34602/SpleeterRT#what-is-the-cost-for-this)

All you need to do is to write a piece of extra code to handle ratio mask, which is you have to run all the sub-models(In 2 stem, it's vocal, accompaniment) and then compute the ratio mask based on 2 sources, here is demo code:

size_t idx1 = offset1 + i;
size_t idx2 = offset2 + i;
float trueS1MaskLeft = leftMask[0][idx2] * leftMask[0][idx2];
float trueS2MaskLeft = leftMask[1][idx2] * leftMask[1][idx2];
float output_sumLeft = trueS1MaskLeft + trueS2MaskLeft + EPSILON;
float trueMask1L = (trueS1MaskLeft + maskFlooring) / output_sumLeft;
float trueMask2L = (trueS2MaskLeft + maskFlooring) / output_sumLeft;
float trueS1MaskRight = rightMask[0][idx2] * rightMask[0][idx2];
float trueS2MaskRight = rightMask[1][idx2] * rightMask[1][idx2];
float output_sumRight = trueS1MaskRight + trueS2MaskRight + EPSILON;
float trueMask1R = (trueS1MaskRight + maskFlooring) / output_sumRight;
float trueMask2R = (trueS2MaskRight + maskFlooring) / output_sumRight;
reL[1][idx2] = reL[0][idx1] * trueMask2L;
imL[1][idx2] = imL[0][idx2] * trueMask2L;
reR[1][idx2] = reR[0][idx1] * trueMask2R;
imR[1][idx2] = imR[0][idx2] * trueMask2R;
reL[0][idx1] = reL[0][idx1] * trueMask1L;
imL[0][idx2] = imL[0][idx2] * trueMask1L;
reR[0][idx1] = reR[0][idx1] * trueMask1R;
imR[0][idx2] = imR[0][idx2] * trueMask1R;

I could no long make changes due to the fact that this repo have been used in commercial product, which is a huge sorry.

**Comment by Jongan** [comment]
Thanks!
